export type RootStackParams = {
  LoadingScreen: undefined;
  LoginScreen: undefined;
  RegisterScreen: undefined;
  PermissionsScreen: undefined;
  TypeClientScreen: undefined;
  HomeClientDriverScreen: undefined;
  HomeClientDeliveryScreen: undefined;
  HomeDriverScreen: undefined;
  HomeDeliveryScreen: undefined;
  ProductsCartScreen: undefined;
  ProductItemScreen: undefined;
  RestaurantScreen: undefined;
  RegisterDriverScreen: undefined;
  WalletScreen: undefined;
  RegisterClientScreen: undefined;
  favoritesScreen: undefined;
  RegisterDeliveryScreen: undefined;
  ProfileDriverScreen: undefined;
  ProfileClientScreen: undefined;
  SettingsScreen: undefined;
  chatBotScreen: undefined;
};
