export type RootStackParams = {
  LoadingScreen: undefined;
  LoginScreen: undefined;
  HomeScreen: undefined;
  RegisterScreen: undefined;
  PermissionsScreen: undefined;
  HomeClientDriverScreen: undefined;
  HomeClientDeliveryScreen: undefined;
  HomeDriverScreen: undefined;
  HomeDeliveryScreen: undefined;
  ProductsCartScreen: undefined;
  ProductItemScreen: undefined;
  RestaurantScreen: undefined;
  RegisterDriverScreen: undefined;
  CouponsScreen: undefined;
  MyCouponsScreen: undefined;
  WalletScreen: undefined;
  RegisterClientScreen: undefined;
  favoritesScreen: undefined;
  RegisterDeliveryScreen: undefined;
  ProfileDriverScreen: undefined;
  ProfileClientScreen: undefined;
  SettingsScreen: undefined;
  chatBotScreen: undefined;
  ErrorScreen: undefined;
  HistoryScreen: undefined;
  RefillsScreen: undefined;

  ShoppingHistoryScreen: undefined;
  ShoppingHistoryItemScreen: undefined;
  HistoryListScreen: undefined;
  CheckoutScreen: undefined;
};
