export type RootStackParams = {
  LoadingScreen: undefined;
  LoginScreen: undefined;
  RegisterScreen: undefined;
  PermissionsScreen: undefined;
  TypeClientScreen: undefined;
  HomeClientDriverScreen: undefined;
  HomeClientDeliveryScreen: undefined;
  HomeDriverScreen: undefined;
  HomeDeliveryScreen: undefined;
  ProductItem: undefined;
  RestaurantScreen: {idRestaurant: number};
  RestaurantList: undefined;
  RegisterDriverScreen: undefined;
  ProductItemScreen: undefined;
  RegisterClientScreen: undefined;
  RegisterDeliveryScreen: undefined;
  ProfileDriverScreen: undefined;
  ProfileClientScreen: undefined;
  SettingsScreen: undefined;
};
